# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\zek\3rd yr comsci\summer\CS 304\soft eng\github\qt\coachselection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(880, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        self.help.setFont(font)
        self.help.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white ;\n"
"color:#5e3b96;\n"
" border-radius:10px;\n"
"}")
        self.help.setObjectName("help")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 0, 421, 121))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../logos/logog.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.BGviolet = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet.setGeometry(QtCore.QRect(0, 0, 961, 121))
        self.BGviolet.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"}")
        self.BGviolet.setText("")
        self.BGviolet.setObjectName("BGviolet")
        self.coachname = QtWidgets.QLabel(self.centralwidget)
        self.coachname.setGeometry(QtCore.QRect(30, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.coachname.setFont(font)
        self.coachname.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.coachname.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.coachname.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.coachname.setObjectName("coachname")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 230, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.booknow1 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1.setGeometry(QtCore.QRect(80, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1.setFont(font)
        self.booknow1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1.setObjectName("booknow1")
        self.BGviolet_2 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_2.setGeometry(QtCore.QRect(20, 140, 291, 341))
        self.BGviolet_2.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_2.setText("")
        self.BGviolet_2.setObjectName("BGviolet_2")
        self.BGviolet_3 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_3.setGeometry(QtCore.QRect(330, 140, 291, 341))
        self.BGviolet_3.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_3.setText("")
        self.BGviolet_3.setObjectName("BGviolet_3")
        self.BGviolet_4 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_4.setGeometry(QtCore.QRect(640, 140, 291, 341))
        self.BGviolet_4.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_4.setText("")
        self.BGviolet_4.setObjectName("BGviolet_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 330, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 370, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_6.setObjectName("label_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../assets/pfp.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(520, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../assets/pfp.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(830, 160, 80, 80))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../assets/pfp.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.coachname_2 = QtWidgets.QLabel(self.centralwidget)
        self.coachname_2.setGeometry(QtCore.QRect(340, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.coachname_2.setFont(font)
        self.coachname_2.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.coachname_2.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.coachname_2.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.coachname_2.setObjectName("coachname_2")
        self.coachname_3 = QtWidgets.QLabel(self.centralwidget)
        self.coachname_3.setGeometry(QtCore.QRect(650, 160, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.coachname_3.setFont(font)
        self.coachname_3.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.coachname_3.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.coachname_3.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.coachname_3.setObjectName("coachname_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(650, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(340, 230, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(340, 250, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(340, 330, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(340, 370, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_15.setObjectName("label_15")
        self.booknow1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1_2.setGeometry(QtCore.QRect(400, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1_2.setFont(font)
        self.booknow1_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1_2.setObjectName("booknow1_2")
        self.booknow1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1_3.setGeometry(QtCore.QRect(710, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1_3.setFont(font)
        self.booknow1_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1_3.setObjectName("booknow1_3")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(650, 370, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_16.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(650, 330, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(650, 250, 271, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_18.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(650, 230, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_19.setObjectName("label_19")
        self.BGviolet_3.raise_()
        self.BGviolet_2.raise_()
        self.BGviolet.raise_()
        self.help.raise_()
        self.label_12.raise_()
        self.coachname.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.booknow1.raise_()
        self.BGviolet_4.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.coachname_2.raise_()
        self.coachname_3.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.booknow1_2.raise_()
        self.booknow1_3.raise_()
        self.label_16.raise_()
        self.label_17.raise_()
        self.label_18.raise_()
        self.label_19.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.coachname.setText(_translate("MainWindow", "Coach Jeffrey"))
        self.label_2.setText(_translate("MainWindow", "Jeffrey E. Stonks"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>Experience:</p></body></html>"))
        self.booknow1.setText(_translate("MainWindow", "Book now"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Fitness Trainer 2010 - Present</span></p><p><span style=\" color:#ffffff;\">- Professional Bodybuilder 2000-2005</span></p><p><span style=\" color:#ffffff;\">- Nutrition Advisor 2015 - Present</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Specialties:</p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Boxing</span></p><p><span style=\" color:#ffffff;\">- Muay Thai</span></p></body></html>"))
        self.coachname_2.setText(_translate("MainWindow", "Coach Jeffrey"))
        self.coachname_3.setText(_translate("MainWindow", "Coach Jeffrey"))
        self.label_9.setText(_translate("MainWindow", "Jeffrey E. Stonks"))
        self.label_10.setText(_translate("MainWindow", "Jeffrey E. Stonks"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Experience:</p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Fitness Trainer 2010 - Present</span></p><p><span style=\" color:#ffffff;\">- Professional Bodybuilder 2000-2005</span></p><p><span style=\" color:#ffffff;\">- Nutrition Advisor 2015 - Present</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Specialties:</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Boxing</span></p><p><span style=\" color:#ffffff;\">- Muay Thai</span></p></body></html>"))
        self.booknow1_2.setText(_translate("MainWindow", "Book now"))
        self.booknow1_3.setText(_translate("MainWindow", "Book now"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Boxing</span></p><p><span style=\" color:#ffffff;\">- Muay Thai</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>Specialties:</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">- Fitness Trainer 2010 - Present</span></p><p><span style=\" color:#ffffff;\">- Professional Bodybuilder 2000-2005</span></p><p><span style=\" color:#ffffff;\">- Nutrition Advisor 2015 - Present</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>Experience:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
