# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\zek\3rd yr comsci\summer\CS 304\soft eng\github\qt\finalizeschedule.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1523, 898)
        MainWindow.setStyleSheet("QMainWindow\n"
"{\n"
"background:white;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 121))
        self.widget_2.setStyleSheet("QWidget\n"
"{\n"
"background: #5e3b96;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(435, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.widget_2)
        self.label_13.setMaximumSize(QtCore.QSize(421, 121))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../logos/logog.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        spacerItem1 = QtWidgets.QSpacerItem(435, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.back = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back.sizePolicy().hasHeightForWidth())
        self.back.setSizePolicy(sizePolicy)
        self.back.setMinimumSize(QtCore.QSize(75, 45))
        self.back.setMaximumSize(QtCore.QSize(550, 350))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #5e3b96;\n"
"color:white;\n"
" border-radius:20px;\n"
"}")
        self.back.setObjectName("back")
        self.verticalLayout_3.addWidget(self.back)
        spacerItem2 = QtWidgets.QSpacerItem(15, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.help = QtWidgets.QPushButton(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.help.sizePolicy().hasHeightForWidth())
        self.help.setSizePolicy(sizePolicy)
        self.help.setMinimumSize(QtCore.QSize(75, 45))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.help.setFont(font)
        self.help.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #5e3b96;\n"
"color:white;\n"
" border-radius:20px;\n"
"}")
        self.help.setObjectName("help")
        self.verticalLayout_3.addWidget(self.help)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_12 = QtWidgets.QWidget(self.widget_5)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.widget_12)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(38)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"color:#5e3b96;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"color:#5e3b96;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel\n"
"{\n"
"color:#5e3b96;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"color:#5e3b96;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_9.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel\n"
"{\n"
"color:#5e3b96;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_9.addWidget(self.label_7)
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 50)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.confirm = QtWidgets.QPushButton(self.widget_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confirm.sizePolicy().hasHeightForWidth())
        self.confirm.setSizePolicy(sizePolicy)
        self.confirm.setMinimumSize(QtCore.QSize(180, 50))
        self.confirm.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(22)
        self.confirm.setFont(font)
        self.confirm.setStyleSheet("QPushButton\n"
"{\n"
"background-color:#5e3b96;\n"
"color:white;\n"
"border-radius:20px;\n"
"}")
        self.confirm.setObjectName("confirm")
        self.horizontalLayout_5.addWidget(self.confirm)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.widget_13)
        self.verticalLayout_7.addWidget(self.widget_12)
        self.horizontalLayout_3.addWidget(self.widget_5)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setStyleSheet("QWidget\n"
"{\n"
"background-color: #5e3b96;\n"
" border-radius:20px;\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_7 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem7 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem7)
        self.label = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem8 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(self.widget_7)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem9 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem9)
        self.verticalLayout.addWidget(self.widget_7)
        self.widget_8 = QtWidgets.QWidget(self.widget_6)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.widget_8)
        self.widget_9.setStyleSheet("")
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sunday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.sunday.setFont(font)
        self.sunday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.sunday.setObjectName("sunday")
        self.verticalLayout_4.addWidget(self.sunday)
        self.monday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.monday.setFont(font)
        self.monday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.monday.setObjectName("monday")
        self.verticalLayout_4.addWidget(self.monday)
        self.tuesday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.tuesday.setFont(font)
        self.tuesday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.tuesday.setObjectName("tuesday")
        self.verticalLayout_4.addWidget(self.tuesday)
        self.wednesday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.wednesday.setFont(font)
        self.wednesday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.wednesday.setObjectName("wednesday")
        self.verticalLayout_4.addWidget(self.wednesday)
        self.thursday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.thursday.setFont(font)
        self.thursday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.thursday.setObjectName("thursday")
        self.verticalLayout_4.addWidget(self.thursday)
        self.friday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.friday.setFont(font)
        self.friday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.friday.setObjectName("friday")
        self.verticalLayout_4.addWidget(self.friday)
        self.saturday = QtWidgets.QCheckBox(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.saturday.setFont(font)
        self.saturday.setStyleSheet("QCheckBox\n"
"{\n"
"color:white;\n"
"}")
        self.saturday.setObjectName("saturday")
        self.verticalLayout_4.addWidget(self.saturday)
        self.horizontalLayout_4.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_8)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.sunstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.sunstart.setFont(font)
        self.sunstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.sunstart.setObjectName("sunstart")
        self.verticalLayout_5.addWidget(self.sunstart)
        self.monstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.monstart.setFont(font)
        self.monstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.monstart.setObjectName("monstart")
        self.verticalLayout_5.addWidget(self.monstart)
        self.tuesstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.tuesstart.setFont(font)
        self.tuesstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.tuesstart.setObjectName("tuesstart")
        self.verticalLayout_5.addWidget(self.tuesstart)
        self.wedstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.wedstart.setFont(font)
        self.wedstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.wedstart.setObjectName("wedstart")
        self.verticalLayout_5.addWidget(self.wedstart)
        self.thursstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.thursstart.setFont(font)
        self.thursstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.thursstart.setObjectName("thursstart")
        self.verticalLayout_5.addWidget(self.thursstart)
        self.fristart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.fristart.setFont(font)
        self.fristart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.fristart.setObjectName("fristart")
        self.verticalLayout_5.addWidget(self.fristart)
        self.satstart = QtWidgets.QTimeEdit(self.widget_10)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.satstart.setFont(font)
        self.satstart.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.satstart.setObjectName("satstart")
        self.verticalLayout_5.addWidget(self.satstart)
        self.horizontalLayout_4.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_8)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sunend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.sunend.setFont(font)
        self.sunend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.sunend.setObjectName("sunend")
        self.verticalLayout_6.addWidget(self.sunend)
        self.monend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.monend.setFont(font)
        self.monend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.monend.setObjectName("monend")
        self.verticalLayout_6.addWidget(self.monend)
        self.tuesend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.tuesend.setFont(font)
        self.tuesend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.tuesend.setObjectName("tuesend")
        self.verticalLayout_6.addWidget(self.tuesend)
        self.wedend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.wedend.setFont(font)
        self.wedend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.wedend.setObjectName("wedend")
        self.verticalLayout_6.addWidget(self.wedend)
        self.thursend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.thursend.setFont(font)
        self.thursend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.thursend.setObjectName("thursend")
        self.verticalLayout_6.addWidget(self.thursend)
        self.fridayend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.fridayend.setFont(font)
        self.fridayend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.fridayend.setObjectName("fridayend")
        self.verticalLayout_6.addWidget(self.fridayend)
        self.satend = QtWidgets.QTimeEdit(self.widget_11)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        self.satend.setFont(font)
        self.satend.setStyleSheet("QTimeEdit{\n"
"color:white;\n"
"}")
        self.satend.setObjectName("satend")
        self.verticalLayout_6.addWidget(self.satend)
        self.horizontalLayout_4.addWidget(self.widget_11)
        self.verticalLayout.addWidget(self.widget_8)
        self.horizontalLayout_3.addWidget(self.widget_6)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.label_3.setText(_translate("MainWindow", "Finalize your Schedule"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Mark the checkboxes on the day of which </p><p>you want to have training sessions.</p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; color:#67389a;\">Select your preferred start time</span></p><p><span style=\" font-weight:700; color:#67389a;\">of training sessions.</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; color:#67389a;\">Each training session has a duration </span></p><p><span style=\" font-weight:700; color:#67389a;\">of one (1) hour.</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; color:#67389a;\">After selecting your desired schedule, </span></p><p><span style=\" font-weight:700; color:#67389a;\">press the confirm button to finalize </span></p><p><span style=\" font-weight:700; color:#67389a;\">your selection.</span></p></body></html>"))
        self.confirm.setText(_translate("MainWindow", "Confirm"))
        self.label.setText(_translate("MainWindow", "START TIME"))
        self.label_2.setText(_translate("MainWindow", "END TIME"))
        self.sunday.setText(_translate("MainWindow", "SUNDAY"))
        self.monday.setText(_translate("MainWindow", "MONDAY"))
        self.tuesday.setText(_translate("MainWindow", "TUESDAY"))
        self.wednesday.setText(_translate("MainWindow", "WEDNESDAY"))
        self.thursday.setText(_translate("MainWindow", "THURSDAY"))
        self.friday.setText(_translate("MainWindow", "FRIDAY"))
        self.saturday.setText(_translate("MainWindow", "SATURDAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
