# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\zek\3rd yr comsci\summer\CS 304\soft eng\github\qt\numberofsessions.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 0, 421, 121))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../logos/logog.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.BGviolet = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet.setGeometry(QtCore.QRect(0, 0, 961, 121))
        self.BGviolet.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"}")
        self.BGviolet.setText("")
        self.BGviolet.setObjectName("BGviolet")
        self.numofsessions = QtWidgets.QLabel(self.centralwidget)
        self.numofsessions.setGeometry(QtCore.QRect(290, 140, 381, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.numofsessions.setFont(font)
        self.numofsessions.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.numofsessions.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.numofsessions.setScaledContents(True)
        self.numofsessions.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.numofsessions.setObjectName("numofsessions")
        self.booknow1 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1.setGeometry(QtCore.QRect(390, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1.setFont(font)
        self.booknow1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1.setObjectName("booknow1")
        self.BGviolet_2 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_2.setGeometry(QtCore.QRect(290, 140, 381, 361))
        self.BGviolet_2.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_2.setText("")
        self.BGviolet_2.setObjectName("BGviolet_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(340, 260, 281, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 131, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #5e3b96;\n"
"color:white;\n"
" border-radius:20px;\n"
"}")
        self.back.setObjectName("back")
        self.numofsessionsspinbox = QtWidgets.QSpinBox(self.centralwidget)
        self.numofsessionsspinbox.setGeometry(QtCore.QRect(440, 350, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.numofsessionsspinbox.setFont(font)
        self.numofsessionsspinbox.setStyleSheet("")
        self.numofsessionsspinbox.setObjectName("numofsessionsspinbox")
        self.BGviolet_2.raise_()
        self.BGviolet.raise_()
        self.label_12.raise_()
        self.numofsessions.raise_()
        self.booknow1.raise_()
        self.label_4.raise_()
        self.back.raise_()
        self.numofsessionsspinbox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.numofsessions.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Select the Number</span></p><p align=\"center\"><span style=\" font-size:22pt;\">of Sessions</span></p></body></html>"))
        self.booknow1.setText(_translate("MainWindow", "Proceed"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">- Adding more sessions would require another booking transaction</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
