# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\zek\3rd yr comsci\summer\CS 304\soft eng\github\qt\packageselection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setGeometry(QtCore.QRect(880, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        self.help.setFont(font)
        self.help.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white ;\n"
"color:#5e3b96;\n"
" border-radius:10px;\n"
"}")
        self.help.setObjectName("help")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 0, 421, 121))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../logos/logog.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.BGviolet = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet.setGeometry(QtCore.QRect(0, 0, 961, 121))
        self.BGviolet.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"}")
        self.BGviolet.setText("")
        self.BGviolet.setObjectName("BGviolet")
        self.package_2 = QtWidgets.QLabel(self.centralwidget)
        self.package_2.setGeometry(QtCore.QRect(180, 160, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.package_2.setFont(font)
        self.package_2.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.package_2.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.package_2.setScaledContents(True)
        self.package_2.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.package_2.setObjectName("package_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(180, 250, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.booknow1 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1.setGeometry(QtCore.QRect(180, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1.setFont(font)
        self.booknow1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1.setObjectName("booknow1")
        self.BGviolet_2 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_2.setGeometry(QtCore.QRect(120, 140, 291, 341))
        self.BGviolet_2.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_2.setText("")
        self.BGviolet_2.setObjectName("BGviolet_2")
        self.BGviolet_3 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_3.setGeometry(QtCore.QRect(560, 140, 291, 341))
        self.BGviolet_3.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_3.setText("")
        self.BGviolet_3.setObjectName("BGviolet_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 300, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.package_3 = QtWidgets.QLabel(self.centralwidget)
        self.package_3.setGeometry(QtCore.QRect(620, 160, 171, 91))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.package_3.setFont(font)
        self.package_3.setLayoutDirection(QtCore.Qt.Qt::LayoutDirection::LeftToRight)
        self.package_3.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.package_3.setScaledContents(True)
        self.package_3.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignVCenter)
        self.package_3.setObjectName("package_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(620, 250, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(590, 300, 231, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_13.setScaledContents(True)
        self.label_13.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignLeading|QtCore.Qt.Qt::AlignmentFlag::AlignLeft|QtCore.Qt.Qt::AlignmentFlag::AlignTop)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.booknow1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1_2.setGeometry(QtCore.QRect(620, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1_2.setFont(font)
        self.booknow1_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1_2.setObjectName("booknow1_2")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 131, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #5e3b96;\n"
"color:white;\n"
" border-radius:20px;\n"
"}")
        self.back.setObjectName("back")
        self.BGviolet_3.raise_()
        self.BGviolet_2.raise_()
        self.BGviolet.raise_()
        self.help.raise_()
        self.label_12.raise_()
        self.package_2.raise_()
        self.label_2.raise_()
        self.booknow1.raise_()
        self.label_4.raise_()
        self.package_3.raise_()
        self.label_9.raise_()
        self.label_13.raise_()
        self.booknow1_2.raise_()
        self.back.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.package_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Private<br/>Package</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "₱2,000 per session"))
        self.booknow1.setText(_translate("MainWindow", "Book now"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">- Training Sessions conducted with the coach are done one on one</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Other details</span></p></body></html>"))
        self.package_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Private<br/>Package</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "₱1,500 per session"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; color:#ffffff;\">- Training Sessions conducted with the coach are done one on one</span></p><p><span style=\" font-size:10pt; color:#ffffff;\">- Other details</span></p></body></html>"))
        self.booknow1_2.setText(_translate("MainWindow", "Book now"))
        self.back.setText(_translate("MainWindow", "back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
