# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\zek\3rd yr comsci\summer\CS 304\soft eng\github\qt\paymentverification.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(260, 0, 421, 121))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("D:\\zek\\3rd yr comsci\\summer\\CS 304\\soft eng\\github\\qt\\../logos/logog.jpg"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.BGviolet = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet.setGeometry(QtCore.QRect(0, 0, 961, 121))
        self.BGviolet.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"}")
        self.BGviolet.setText("")
        self.BGviolet.setObjectName("BGviolet")
        self.payatcounter = QtWidgets.QLabel(self.centralwidget)
        self.payatcounter.setGeometry(QtCore.QRect(590, 160, 341, 111))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.payatcounter.setFont(font)
        self.payatcounter.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.payatcounter.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.payatcounter.setScaledContents(True)
        self.payatcounter.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.payatcounter.setObjectName("payatcounter")
        self.booknow1 = QtWidgets.QPushButton(self.centralwidget)
        self.booknow1.setGeometry(QtCore.QRect(680, 430, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        self.booknow1.setFont(font)
        self.booknow1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:white;\n"
"color:#5e3b96;\n"
"border-radius:10px;\n"
"}")
        self.booknow1.setObjectName("booknow1")
        self.BGviolet_2 = QtWidgets.QLabel(self.centralwidget)
        self.BGviolet_2.setGeometry(QtCore.QRect(590, 150, 341, 331))
        self.BGviolet_2.setStyleSheet("QLabel\n"
"{\n"
"background: #5e3b96;\n"
"border-radius:20px;\n"
"}")
        self.BGviolet_2.setText("")
        self.BGviolet_2.setObjectName("BGviolet_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(640, 270, 251, 101))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel\n"
"{\n"
"color:white;\n"
"}")
        self.label_4.setScaledContents(True)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(10, 131, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton\n"
"{\n"
"background-color: #5e3b96;\n"
"color:white;\n"
" border-radius:20px;\n"
"}")
        self.back.setObjectName("back")
        self.finalizelbl = QtWidgets.QLabel(self.centralwidget)
        self.finalizelbl.setGeometry(QtCore.QRect(90, 150, 471, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.finalizelbl.setFont(font)
        self.finalizelbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.finalizelbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.finalizelbl.setScaledContents(True)
        self.finalizelbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.finalizelbl.setObjectName("finalizelbl")
        self.coachlbl = QtWidgets.QLabel(self.centralwidget)
        self.coachlbl.setGeometry(QtCore.QRect(50, 210, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.coachlbl.setFont(font)
        self.coachlbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.coachlbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.coachlbl.setScaledContents(True)
        self.coachlbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.coachlbl.setObjectName("coachlbl")
        self.progplanlbl = QtWidgets.QLabel(self.centralwidget)
        self.progplanlbl.setGeometry(QtCore.QRect(50, 260, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.progplanlbl.setFont(font)
        self.progplanlbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.progplanlbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.progplanlbl.setScaledContents(True)
        self.progplanlbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.progplanlbl.setObjectName("progplanlbl")
        self.packagelbl = QtWidgets.QLabel(self.centralwidget)
        self.packagelbl.setGeometry(QtCore.QRect(50, 310, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.packagelbl.setFont(font)
        self.packagelbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.packagelbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.packagelbl.setScaledContents(True)
        self.packagelbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.packagelbl.setObjectName("packagelbl")
        self.noofsesslbl = QtWidgets.QLabel(self.centralwidget)
        self.noofsesslbl.setGeometry(QtCore.QRect(50, 370, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.noofsesslbl.setFont(font)
        self.noofsesslbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.noofsesslbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.noofsesslbl.setScaledContents(True)
        self.noofsesslbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.noofsesslbl.setObjectName("noofsesslbl")
        self.totalamtlbl = QtWidgets.QLabel(self.centralwidget)
        self.totalamtlbl.setGeometry(QtCore.QRect(50, 420, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(20)
        self.totalamtlbl.setFont(font)
        self.totalamtlbl.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.totalamtlbl.setStyleSheet("QLabel\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.totalamtlbl.setScaledContents(True)
        self.totalamtlbl.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.totalamtlbl.setObjectName("totalamtlbl")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 211, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("QLineEdit\n"
"{\n"
"color: #5e3b96;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(270, 260, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(200, 310, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 370, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(270, 420, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(640, 380, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        font.setBold(True)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.BGviolet_2.raise_()
        self.BGviolet.raise_()
        self.label_12.raise_()
        self.payatcounter.raise_()
        self.booknow1.raise_()
        self.label_4.raise_()
        self.back.raise_()
        self.finalizelbl.raise_()
        self.coachlbl.raise_()
        self.progplanlbl.raise_()
        self.packagelbl.raise_()
        self.noofsesslbl.raise_()
        self.totalamtlbl.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()
        self.lineEdit_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.payatcounter.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">Payment at the<br/>Counter</span></p></body></html>"))
        self.booknow1.setText(_translate("MainWindow", "Proceed"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">- After completing the payment at the counter, please wait for the admin to enter the code.</span></p></body></html>"))
        self.back.setText(_translate("MainWindow", "back"))
        self.finalizelbl.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:26pt;\">Finalize your Selections</span></p></body></html>"))
        self.coachlbl.setText(_translate("MainWindow", "<html><head/><body><p>Coach:</p></body></html>"))
        self.progplanlbl.setText(_translate("MainWindow", "<html><head/><body><p>Program Plan:</p></body></html>"))
        self.packagelbl.setText(_translate("MainWindow", "<html><head/><body><p>Package:</p></body></html>"))
        self.noofsesslbl.setText(_translate("MainWindow", "<html><head/><body><p>Number of Sessions:</p></body></html>"))
        self.totalamtlbl.setText(_translate("MainWindow", "<html><head/><body><p>Total Amount:</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
